Introducing the notion of shards as an encapsulation of primary and s…
ashwanthkumar/suuchi pull request #59
Opened 2016-11-29 14:19 UTC by gsriram7

…econdary partitions

2016-11-29 18:01 UTC, gsriram7 commented
@ashwanthkumar

2016-11-30 02:10 UTC, ashwanthkumar requested changes

2016-11-30 02:10 UTC, ashwanthkumar commented on suuchi-core/src/main/scala/in/ashwanthkumar/suuchi/partitioner/CHRWithShards.scala
> +case class Shard(primaryPartition: VNode, follower: List[VNode]) {
Can we please add a notion of `id` / `name` to Shard?

2016-11-30 02:10 UTC, ashwanthkumar commented on suuchi-core/src/main/scala/in/ashwanthkumar/suuchi/partitioner/CHRWithShards.scala
> +case class Shard(primaryPartition: VNode, follower: List[VNode]) {
For cases where we know they're primary and followers - it would be best if we can abstract those away as `MemberAddress` isn't? `VNode` doesn't make sense anymore to me. What do you think?

2016-11-30 02:10 UTC, ashwanthkumar commented on suuchi-core/src/main/scala/in/ashwanthkumar/suuchi/partitioner/CHRWithShards.scala
> +  val sortedMap = new util.TreeMap[Integer, Shard]()
Can we please mark this `private`? This is exposed as `public`.

2016-11-30 02:10 UTC, ashwanthkumar commented on suuchi-core/src/main/scala/in/ashwanthkumar/suuchi/partitioner/CHRWithShards.scala
> +class CHRWithShards(hashFn: Hash, partitionsPerNode: Int, replicationFactor: Int = 2) {
It would be nice if we don't have defaults as part of the class and move them as part of the companion object or place them where it's actually being used.

2016-11-30 02:10 UTC, ashwanthkumar commented on suuchi-core/src/main/scala/in/ashwanthkumar/suuchi/partitioner/CHRWithShards.scala
> +  private def hash(shard: Shard): Int = hashFn.hash(shard.key.getBytes)
Please move all `private` methods to the bottom of the class.

2016-11-30 02:10 UTC, ashwanthkumar commented on suuchi-core/src/main/scala/in/ashwanthkumar/suuchi/partitioner/CHRWithShards.scala
> +  def key = primaryPartition.node.host + "_" + primaryPartition.node.port + "_" + primaryPartition.nodeReplicaId
What's a `nodeReplicaId` ? Did it come in as part of #58 ?

2016-11-30 02:10 UTC, ashwanthkumar commented on suuchi-core/src/main/scala/in/ashwanthkumar/suuchi/partitioner/CHRWithShards.scala
> +    (1 to partitionsPerNode).map(i => Shard(VNode(node, 1, Primary), followers(nodes.filterNot(_.equals(node))))).foreach { shard =>
Selva, Can we please have a test for this? It doesn't look right to me.

2016-11-30 02:10 UTC, ashwanthkumar commented on suuchi-core/src/main/scala/in/ashwanthkumar/suuchi/partitioner/CHRWithShards.scala
> +case class Shard(primaryPartition: VNode, follower: List[VNode]) {
Also I thought we were using `partitions` and not `partitionsPerNode` ?

2016-11-30 02:12 UTC, ashwanthkumar commented
@gsriram7 Can we also please add tests to this PR? Also can you print the CHRing with some sample data and see if you can plot it on a ring like structure by taking their ranges into account.

2016-12-02 13:14 UTC, ashwanthkumar commented
Closing this in favor of #60

2016-12-02 13:14 UTC, closed without merging